# Defaults for image training.

in_channels: 2
out_channels: 4
num_channels: 256
num_heads: 4
num_res_blocks: 1
attention_resolutions: "16"
dropout: 0.0
resamp_with_conv: True
learn_sigma: True
use_scale_shift_norm: true
use_fp16: false
resblock_updown: true
num_heads_upsample: -1
var_type: 'fixedsmall'
num_head_channels: 64
image_size: 320
class_cond: false
use_new_attention_order: false

model_path: models/fastmri.pt
