conditioning:
  method: ps
  params:
    scale: 0.5

data:
  name: fastknee_mri
  root: ./data/samples/mri

measurement:
  operator:
    name: mri
  mask_opt:
    mask_type: random
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
